name: Testing

on:
  push:
    branches:
      - master
  pull_request_review:
    types:
      - submitted
    branches:
      - master
jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test with Gradle
        run: echo Hello 

      - name: Get the version
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}-rc"

      - name: Set environment variable
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}-rc" >> $GITHUB_ENV

      - name: Print the value of tag
        run: echo ${{ env.BRANCH_NAME }}     
        
