name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test with Gradle
        run: echo Hello 